config/routes.rb
Dart::Application.routes.draw do
  resources :locations

  resources :orders

  devise_for :users
  match '/language/:lang_cut' => 'welcomes#set_lang'
  match '/unit_images/upload' => 'unit_images#upload'
  match '/unit_images/update/:id/:cover/:preview/:title' => 'unit_images#update'
  match '/unit_images/destroy/:id' => 'unit_images#destroy'
  resources :unit_images

  scope '/:locale', :locale => /en|ru/ do
    #resources :feedbacks
    #resources :unit_images
    #resources :unit_files

    resources :units do
      collection do
        get '/new/:parent_id' => 'units#new'
      end
    end

    resources :welcomes

    match '/access_denied' => 'error#access_denied', :as => :access_denied
    match '/not_found' => 'error#not_found', :as => :not_found

    match '/:short_url' => 'units#show', :as => :unit_by_short_url
  end

  root :to => 'welcomes#index'
end

app/models/unit.rb
class Unit < ActiveRecord::Base

  #self.per_page = 12
  #belongs_to :author, :class_name => 'User'
  belongs_to :unit, :foreign_key => :parent_id
  has_many :units, :foreign_key => :parent_id, :order => 'unit_order'
  has_many :unit_images

  validates_presence_of :title, :locale#, :short_url
  validates_uniqueness_of :short_url

  attr_accessible :locale, :title, :parent_id, :welcome_slider, :description, :content, :layout, :unit_order, :short_url, :seo_title, :seo_keywords, :seo_description, :created_at, :preview_id

  attr_writer :preview_id
  attr_reader :preview_id

  #scope :main_menu, where(:parent_id => nil).order(:unit_order)
  scope :main_menu, lambda { |locale| where(:parent_id => nil).where("locale = ?", locale).order(:unit_order) }

  #default_scope order("created_at DESC")
  #scope :side_bar, order("created_at DESC").limit(3)
  #scope :side_bar, lambda { |post| where("id <> ?", post.id).order("created_at DESC").limit(3) }

  before_save :generate_short_url
  #after_create :update_attachements

  def initialize(*args)
    super
    self.preview_id = rand(99999999) + 99999999 if self.preview_id.nil? && self.new_record?
  end

  def super_unit
    @super_unit = self
    loop do
      @super_unit = @super_unit.unit() unless @super_unit.parent_id.nil?
      break if @super_unit.nil? || @super_unit.parent_id.nil?
    end
    @super_unit
  end

  def get_id
    self.id || self.preview_id
  end

  def get_cover
    cover_images = UnitImage.find_all_by_unit_id_and_cover(self.id, true)
    unless cover_images.empty?
      cover_images[rand(cover_images.size())]
    else
      UnitImage.find_by_unit_id(self.id) || UnitImage.new
    end
  end

  def get_covers
    cover_images = UnitImage.find_all_by_unit_id_and_cover(self.id, true)
    if cover_images.empty? || cover_images.nil?
      cover_images = [UnitImage.find_by_unit_id(self.id) || UnitImage.new]
    end
    cover_images
  end

  def get_preview
    preview_images = UnitImage.find_all_by_unit_id_and_preview(self.id, true)

    unless preview_images.empty?
      preview_images[rand(preview_images.size())]
    else
      UnitImage.find_by_unit_id(self.id) || UnitImage.new
    end
  end


  def tree
    tree = []
    units = Unit.main_menu
    units.each do |fl|
      tree << fl
      slc = fl.units
      slc.each do |sl|
        sl.title = "+" + sl.title
        tree << sl
        tlc = sl.units
        tlc.each do |tl|
          tl.title = "++" + tl.title
          tree << tl
        end if tlc
      end if slc
    end
    tree
  end

  private

  def generate_short_url
    unless self.title.blank?
      self.short_url = Russian.transliterate(self.title.gsub(' ', '-')).downcase if self.short_url.blank?
    end
  end

  def self.tree
    tree = []
    units = Unit.main_menu(I18n.locale)
    units.each do |fl|
      tree << fl
      slc = fl.units
      slc.each do |sl|
        sl.title = "+" + sl.title
        tree << sl
        tlc = sl.units
        tlc.each do |tl|
          tl.title = "++" + tl.title
          tree << tl
        end if tlc
      end if slc
    end
    tree
  end

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  load_and_authorize_resource

  def index
    @units = Unit.order("layout, id desc")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @units }
    end
  end

  def show
    @unit = Unit.find_by_short_url_and_locale(params[:short_url], I18n.locale) if params[:short_url]
    raise NotFound unless @unit

     if @unit.layout == "news"
       @news = Unit.where("parent_id = ? and units.locale = ?", @unit.id, I18n.locale).order("id desc").all
       @covers = UnitImage.includes(:unit).where("units.locale = ? and units.welcome_slider = ? and unit_images.cover = ?", I18n.locale, true, true).all
     end

     if @unit.layout == "news_single"
       @news = Unit.where("parent_id = ? and units.locale = ?", @unit.super_unit.id, I18n.locale).order("id desc").all
       @covers = UnitImage.includes(:unit).where("units.locale = ? and units.welcome_slider = ? and unit_images.cover = ?", I18n.locale, true, true).all
     end

     if @unit.layout == "projects"
       @covers = UnitImage.includes(:unit).where("units.layout = ? and units.locale = ? and unit_images.cover = ?", "project", I18n.locale, true).all
     end

     if @unit.layout == "services"
       @covers = UnitImage.includes(:unit).where("units.layout = ? and units.locale = ? and unit_images.cover = ?", "service", I18n.locale, true).all
     end

     if @unit.layout == "contacts"
       @locations = Location.where(:locale => I18n.locale).all.to_gmaps4rails
     end

     if @unit.layout == "order"
       @order = Order.new
       #@covers = UnitImage.includes(:unit).where("units.layout = ? and units.locale = ? and unit_images.cover = ?", "service", I18n.locale, true).all
     end

    #if @unit.short_url == "press-about-company"
    #  year = params[:year] if !params[:year].nil?
    #  if year.nil?
    #    @units = Unit.press.paginate(:page => params[:page])
    #  else
    #    @units = Unit.press.where("created_at between ? AND ?", "#{year}-01-01 00:00:00".to_datetime(), "#{year}-12-31 23:59:59".to_datetime()).paginate(:page => params[:page])
    #  end
    #  @years = Unit.find_by_sql("SELECT DISTINCT strftime('%Y', created_at) year from units where parent_id = 13 ORDER BY created_at DESC")
    #end

    respond_to do |format|
      format.html {
        if @unit.layout == "order"
          render action: @unit.layout, :layout => "order"
        else
          render action: @unit.layout
        end
      }
      format.xml { render xml: @unit }
      format.json { render json: @unit }
    end
  end

  def new
    @unit.parent_id = params[:parent_id] if params[:parent_id]
    @unit.layout = @unit.unit.layout if params[:parent_id]

    respond_to do |format|
      format.html { render layout: "editor" }
      format.json { render json: @unit }
    end
  end

  def edit
    @unit = Unit.find(params[:id])
    render layout: "editor"
  end

  def create
    @unit = Unit.new(params[:unit])

    respond_to do |format|
      if @unit.save
        format.html { redirect_to root_url, notice: 'Unit was successfully created.' }
        format.json { render json: @unit, status: :created, location: @unit }
      else
        format.html { render action: "new", layout: "editor" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @unit = Unit.find(params[:id])

    respond_to do |format|
      if @unit.update_attributes(params[:unit])
        format.html { redirect_to root_url, notice: 'Unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit", layout: "editor" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_about_side_bar.html.erb
<div id="sidebar">
  <div class="description about_title">
    <h1><%= @unit.title %><%= render "units/admin_panel", :target => @unit %></h1>
    <div class="top"></div>
    <div class="menu_wrapper">
      <ul class="menu_about">
        <% @unit.units.each do |unit| %>
            <li <%= "class='current'" if @unit && unit == @unit %>>
              <%= link_to raw("<span>#{unit.title}</span>"), unit_by_short_url_path(unit.short_url), :class => "red" %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/units/_about_us_side_bar.html.erb
<div id="sidebar">
  <div class="description about_title">
    <h1><%= link_to @unit.unit.title, unit_by_short_url_path(@unit.unit.short_url) %><%= link_to "", unit_by_short_url_path(@unit.unit.short_url), :class => "back" %></h1>

    <div class="top"></div>
    <div class="menu_wrapper">
      <ul class="menu_about">
        <li class="current no_border">
          <%= link_to raw("<span>#{@unit.title}</span>"), unit_by_short_url_path(@unit.short_url), :class => "red" %>
        </li>
      </ul>
      <div class="bottom"></div>
      <div class="text">
        <p>
          <%= raw @unit.content %>
        </p>
        <%= render "units/admin_panel", :target => @unit %>
      </div>
    </div>
  </div>
</div>

app/views/units/_admin_panel.html.erb
<% if can?(Unit, :edit) || can?(Unit, :destroy) || can?(Unit, :create) %>
    <div class="panel-admin">
      <ul>
        <% if can?(Unit, :edit) %>
            <li class="ui-corner-all">
              <%= link_to t('backend.actions.edit'), edit_unit_path(target), :class => "ui-icon ui-icon-pencil", :title => t('backend.actions.edit') %>
            </li>
        <% end %>
        <% if can?(Unit, :destroy) %>
            <li class="ui-corner-all">
              <%= link_to(t('backend.actions.destroy'), target, :class => "ui-icon ui-icon-cart", :confirm => t('backend.actions.are_you_sure'), :method => :delete, :title => t('backend.actions.destroy')) %>
            </li>
        <% end %>
        <% if can?(Unit, :create) %>
            <li class="ui-corner-all">
              <%= link_to t('helpers.submit.create'), "/#{I18n.locale}/units/new/#{target.id}", :class => "ui-icon ui-icon-plus", :title => t('helpers.submit.create') %>
            </li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/units/_form.html.erb
<%= form_for(@unit, :html => {:multipart => true}) do |f| %>
    <% if @unit.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

          <ul>
            <% @unit.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <div class="half">
        <%= f.label :parent_id %>
        <br/>
        <%= f.collection_select(:parent_id, Unit.tree, :id, :title, :include_blank => "не выбрано") %>
      </div>

      <div class="half">
        <%= f.label :layout %>
        <br/>
        <%= f.collection_select :layout, Layout.collection, :cut, :name, :promt => false %>
      </div>

      <div class="half">
        <%= f.label :locale %>
        <br/>
        <%= f.collection_select(:locale, Language.collection, :cut, :name, {:prompt => false, :selected => I18n.locale}) %>
      </div>

      <div class="half">
        <%= f.label :welcome_slider %>
        <br/>
        <%= f.check_box :welcome_slider %>
      </div>
    </div>

    <div class="field">
      <br/>
      <br/>
      <br/>
      <%= f.label :title %>
      <br/>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <br/>
      <%= f.text_area :description, :class => "description" %>
    </div>
    <div class="field">
      <%= f.label :content %>
      <br/>
      <%= f.text_area :content %>
    </div>
    <div class="field">
      <%= f.label :unit_order %>
      <br/>
      <%= f.number_field :unit_order %>
    </div>
    <div class="field">
      <%= f.label :short_url %>
      <br/>
      <%= f.text_field :short_url %>
    </div>
    <div class="field">
      <%= f.label :seo_title %>
      <br/>
      <%= f.text_field :seo_title %>
    </div>
    <div class="field">
      <%= f.label :seo_keywords %>
      <br/>
      <%= f.text_field :seo_keywords %>
    </div>
    <div class="field">
      <%= f.label :seo_description %>
      <br/>
      <%= f.text_field :seo_description %>
    </div>

    <div class="field">
      <%= render :partial => 'unit_images/files_upload', :locals => {:unit => @unit} %>
    </div>

    <div class="clear"></div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>


<script language="javascript">
    $(document).ready(function () {
        $("#unit_content").markItUp(mySettings);
    });

    function updateStuffImage(stuff_image_id, classname) {
        title = $("#" + classname + "_image_" + stuff_image_id + " input[type='text']").val();
        cover = $("#" + classname + "_image_" + stuff_image_id + " .upload_cover").is(':checked');
        preview = $("#" + classname + "_image_" + stuff_image_id + " .upload_preview").is(':checked');
        if (title == '') {
            title = 'empty'
        }
        $.get("/" + classname + "_images/update/" + stuff_image_id + "/" + cover + "/" + preview + "/" + title);
    }
</script>

app/views/units/_news_side_bar.html.erb
<div id="sidebar">
  <div class="description news_title">
    <h1><%= @unit.title %><%= render "units/admin_panel", :target => @unit %></h1>
    <div class="top"></div>
    <div class="menu_wrapper">
      <ul class="menu_about">
        <% @news.each do |unit| %>
            <li>
              <%= link_to raw("<span>#{unit.title}</span>"), unit_by_short_url_path(unit.short_url), :class => "new" %>
              <div class="news_list">
                <div class="border_right">
                  <%= image_tag unit.get_preview.image(:preview_item), :width => 213, :height => 81, :alt => unit.title, :onclick => "setBackgroundImage('#{unit.get_preview.image()}')" %>
                  <span><%= unit.created_at.strftime("%d.%m.%Y") %></span>
                  <p><%= raw unit.content %></p>
                  <%= render "units/admin_panel", :target => unit %>
                </div>
              </div>
            </li>
        <% end unless @news.nil? %>
      </ul>
    </div>
  </div>
</div>

app/views/units/_projects_side_bar.html.erb
<div id="sidebar">
  <div class="description portfolio_title">
    <h1><%= @unit.title %><%= render "units/admin_panel", :target => @unit %></h1>
    <div class="top"></div>
    <div class="menu_wrapper">
      <ul class="menu_about">
        <% @unit.units.each do |unit| %>
            <li <%= "class='current'" if unit == @unit.units.first %>>
              <%= link_to raw("<span>#{unit.title}</span>"), "", :class => "portfolio" %>
              <% unless unit.units.empty? %>
                  <div class="news_list">
                    <div class="border_right">
                      <ul>
                        <% unit.units.each do |sunit| %>
                            <li>
                              <%= link_to sunit.title, "#" %>
                              <% unless sunit.units.empty? %>
                                  <ul>
                                    <% sunit.units.each do |ssunit| %>
                                        <li>
                                          <%= link_to ssunit.title, unit_by_short_url_path(ssunit.short_url) %>
                                        </li>
                                    <% end %>
                                  </ul>
                              <% end %>
                            </li>
                        <% end %>
                      </ul>
                    </div>
                  </div>
              <% end %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<script type="text/javascript">
    $(function () {
        foldAllItems();

        $(".menu_about > li > a").click(function (e) {
            e.preventDefault();

            if ($(this).parent().hasClass("current")) {
                foldItem($(this).parent().index());
            } else {
                foldAllItems();
                var index = $(this).parent().index();
                unfoldItem(index);
            }
        });

        $(".border_right > ul > li > a").click(function (e) {
            e.preventDefault();

            if ($(this).next().css("display") != "block") {
                $(this).next().css("display", "block");
            } else {
                $(this).next().css("display", "none");
            }
        });
    });

    function foldAllItems() {
        $(".news_list").hide();
        $(".menu_about li").removeClass("current");
    }

    function foldItem(index) {
        $(".menu_about li").eq(index).removeClass("current");
        if ($(".menu_about li").eq(index).find(".news_list").length) {
            $(".menu_about li").eq(index).find(".news_list").hide("blind");
        }
    }

    function unfoldItem(index) {
        $(".menu_about > li").eq(index).addClass("current");
        if ($(".menu_about li").eq(index).find(".news_list").length) {
            $(".menu_about li").eq(index).find(".news_list").show("blind");
        }
    }
</script>

app/views/units/_service_side_bar.html.erb
<div id="sidebar">
  <div class="description service_title">
    <h1><%= link_to @unit.unit.title, unit_by_short_url_path(@unit.unit.short_url) %><%= link_to "", unit_by_short_url_path(@unit.unit.short_url), :class => "back back_2" %></h1>
    <div class="top"></div>
    <div class="menu_wrapper">
      <ul class="menu_about">
        <li class="no_border"><%= link_to raw("<span>#{@unit.title}</span>"), unit_by_short_url_path(@unit.short_url), :class => "blue" %></li>
      </ul>
      <div class="bottom"></div>
      <div class="text">
        <p><%= raw @unit.content %></p>
        <%= render "units/admin_panel", :target => @unit %>
      </div>
    </div>
  </div>
</div>

app/views/units/_services_side_bar.html.erb
<div id="sidebar">
  <div class="description">
    <h1 class="service_title"><%= @unit.title %><%= render "units/admin_panel", :target => @unit %></h1>
    <div class="top"></div>
    <div class="menu_wrapper">
      <ul class="menu_about">
        <% @unit.units.each do |unit| %>
            <li <%= "class='current'" if @unit && unit == @unit %>>
              <%= link_to raw("<span>#{unit.title}</span>"), unit_by_short_url_path(unit.short_url), :class => "blue" %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/units/about.html.erb
<%= render "units/about_side_bar" %>
<%= render "layouts/slider_simple" %>

app/views/units/about_us.html.erb
<%= render "units/about_us_side_bar" %>
<%= render "layouts/slider_simple" %>

app/views/units/clients.html.erb
<div id="clients">
  <% @unit.unit_images.each do |cover| %>
      <div class="client">
        <%= image_tag cover.image.url(:logo_middle), :alt => cover.title %>
      </div>
  <% end %>
  <% if can?(Unit, :edit) %>
      <div class="client">
        <%= render "units/admin_panel", :target => @unit %>
      </div>
  <% end %>
</div>

app/views/units/contacts.html.erb
<%= render "units/contacts_side_bar" %>

<%= gmaps({
                  :map_options => {
                          :auto_zoom => false,
                          :zoom => 12,
                          :do_clustering => true
                  },
                  :markers => {
                          :data => @locations
                  }
          })
%>

<script type="text/javascript">
    var SIDEBAR_HIDDEN = true;

    jQuery(function () {
        $(document).mousemove(function (e) {
            if (e.pageX <= 210 && SIDEBAR_HIDDEN) {
                $("#sidebar").animate({
                    "left":"+=400px"
                }, "slow");
                SIDEBAR_HIDDEN = false;
            }

            if (e.pageX >= 380 && !SIDEBAR_HIDDEN) {
                $("#sidebar").animate({
                    "left":"-=400px"
                }, "slow");
                SIDEBAR_HIDDEN = true;
            }
        });
    });

    $(document).ready(function () {
        map_size();
        $(window).resize(function () {
            map_size();
        });
    });

    function map_size() {
        var viewportwidth;
        var viewportheight;

        // the more standards compliant browsers (mozilla/netscape/opera/IE7) use window.innerWidth and window.innerHeight

        if (typeof window.innerWidth != 'undefined') {
            viewportwidth = window.innerWidth,
                    viewportheight = window.innerHeight
        }

// IE6 in standards compliant mode (i.e. with a valid doctype as the first line in the document)

        else if (typeof document.documentElement != 'undefined'
                && typeof document.documentElement.clientWidth !=
                'undefined' && document.documentElement.clientWidth != 0) {
            viewportwidth = document.documentElement.clientWidth,
                    viewportheight = document.documentElement.clientHeight
        }

        // older versions of IE

        else {
            viewportwidth = document.getElementsByTagName('body')[0].clientWidth,
                    viewportheight = document.getElementsByTagName('body')[0].clientHeight
        }

        $(".map_container").css("width", viewportwidth);
        $(".map_container").css("height", viewportheight);
        $("#map").css("width", viewportwidth);
        $("#map").css("height", viewportheight);
    }
</script>

app/views/units/project.html.erb
<%= render "units/project_side_bar" %>
<%= render "layouts/slider_simple" %>

app/views/units/projects.html.erb
<%= render "layouts/slider" %>
<%= render "units/projects_side_bar" %>