config/routes.rb
Dart::Application.routes.draw do
  resources :locations

  resources :orders

  devise_for :users
  match '/language/:lang_cut' => 'welcomes#set_lang'
  match '/unit_images/upload' => 'unit_images#upload'
  match '/unit_images/update/:id/:cover/:preview/:title' => 'unit_images#update'
  match '/unit_images/destroy/:id' => 'unit_images#destroy'
  resources :unit_images

  scope '/:locale', :locale => /en|ru/ do
    #resources :feedbacks
    #resources :unit_images
    #resources :unit_files

    resources :units do
      collection do
        get '/new/:parent_id' => 'units#new'
      end
    end

    resources :welcomes

    match '/access_denied' => 'error#access_denied', :as => :access_denied
    match '/not_found' => 'error#not_found', :as => :not_found

    match '/:short_url' => 'units#show', :as => :unit_by_short_url
  end

  root :to => 'welcomes#index'
end

app/models/layout.rb
#encoding: utf-8
class Layout
  attr_accessor :name
  attr_accessor :cut

  def self.collection
    list = [
        Layout.new(:name => 'Компания', :cut => "about"),
        Layout.new(:name => 'Компания / О нас', :cut => "about_us"),
        Layout.new(:name => 'Компания / Отзывы', :cut => "about_awards"),
        Layout.new(:name => 'Компания / Партнеры', :cut => "about_partners"),
        Layout.new(:name => 'Услуги', :cut => "services"),
        Layout.new(:name => 'Услуга', :cut => "service"),
        Layout.new(:name => 'Новости', :cut => "news"),
        Layout.new(:name => 'Новость', :cut => "news_single"),
        Layout.new(:name => 'Заявка', :cut => "order"),
        Layout.new(:name => 'Контакты', :cut => "contacts"),
        Layout.new(:name => 'Портфолио', :cut => "projects"),
        Layout.new(:name => 'Клиенты', :cut => "clients"),
        Layout.new(:name => 'Проект', :cut => "project")
    ]
    list
  end

  def self.include?(role_cut)
    collection.each do |role|
      return true if role.cut == role_cut
    end
    false
  end

  def self.by_cut(cut)
    collection.each do |layout|
      return layout.name if layout.cut == cut
    end
    false
  end

  def initialize(hash)
    self.name = hash[:name]
    self.cut = hash[:cut]
  end

end

app/views/layouts/_auth.html.erb
<ul class="margin_top_55 menu_about">
  <% if user_signed_in? %>
      <li class="contact">
        <span>
            <div class="contact_box">
              <h4><%= current_user.email %></h4>
            </div>
        </span>
      </li>
      <li class="contact">
        <span>
            <div class="contact_box">
              <h4>
                <%= link_to "#{t('devise.sessions.my')}", "/users/edit" %>
              </h4>
            </div>
        </span>
      </li>
      <li class="contact">
        <span>
            <div class="contact_box">
              <h4><%= link_to t("devise.sessions.sign_out"), destroy_user_session_path, :method => :delete %></h4>
            </div>
        </span>
      </li>
      <li class="contact">
        <span>
            <div class="contact_box">
              <h4><%= link_to "Общий список страниц", units_path %></h4>
            </div>
        </span>
      </li>
  <% end %>
</ul>

app/views/layouts/_footer.html.erb
<div id="footer">
  <ul>
    <% @main_menu.each_with_index do |unit, i| %>
        <li <%= "class='current'" if @unit && unit === @unit.super_unit %>><%= link_to raw("<span>#{unit.title}</span>"), unit_by_short_url_path(unit.short_url), :class => ( i == 0 ? "menu" : "menu_#{i}") %></li>
    <% end %>
  </ul>
  <p><%= t("activerecord.attributes.welcome.copyright") %></p>

  <div class="social">
    <p><%= t("activerecord.attributes.welcome.follow") %></p>
    <%= link_to image_tag("linkedin.png", :alt => @welcome.seo_title || @welcome.title), "http://linkedin.com", :target => "_blank" %>
    <%= link_to image_tag("face.png", :alt => @welcome.seo_title || @welcome.title), "http://vk.com", :target => "_blank" %>
    <%= link_to image_tag("vk.png", :alt => @welcome.seo_title || @welcome.title), "http://vk.com", :target => "_blank" %>
    <%= link_to image_tag("tw.png", :alt => @welcome.seo_title || @welcome.title), "http://vk.com", :target => "_blank" %>
    <%= link_to image_tag("created_by.png", :alt => "Created by Black Sheep"), "http://black-sheep.ru", :target => "_blank", :title => "Created by Black Sheep" %>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id="header">
  <%= link_to "", root_path, :class => "logo" %>
  <div class="right_block">
    <ul class="language">
      <% Language.collection.each do |locale| %>
          <li><%= link_to image_tag("#{locale.cut}.png", :alt => locale.name), "/language/#{locale.cut}" %></li>
      <% end %>
    </ul>
    <%= link_to t('backend.actions.edit'), edit_welcome_path(@welcome), :class => "ui-icon ui-icon-pencil", :title => t('backend.actions.edit') if can?(Welcome, :edit) %>

    <span>
      <%= @welcome.phone %>
    </span>
  </div>
</div>

app/views/layouts/_info.html.erb
<div class="slide-descriptions">
  <% @top.each do |unit| %>
      <% unit.get_covers.each do |cover| %>
          <div class="sl-descr">
            <div class="title_info">
              <%= unit.title %>
            </div>
            <%= link_to t("activerecord.attributes.unit.more"), unit_by_short_url_path(unit.short_url), :class => "more" %>
          </div>
      <% end %>
  <% end %>
</div>

<div class="info">
</div>

app/views/layouts/_sidebar.html.erb
<div id="sidebar" style="left: -400px;">
  <div class="about">
    <%= raw @welcome.description %>
  </div>
  <% unless @last_news.nil? %>
      <div class="news">
        <%= link_to @last_news.title, unit_by_short_url_path(@last_news.short_url), :class => "title_news" %>
        <p><%= raw @last_news.description %> &#133;<%= link_to t("activerecord.attributes.unit.more").mb_chars.downcase, unit_by_short_url_path(@last_news.short_url) %></p>
      </div>
  <% end %>
</div>

app/views/layouts/_slider.html.erb
<% unless @covers.nil? %>
    <ul class="cb-slideshow">
      <% delay = 8 %>

      <% @covers.each do |cover| %>
          <li>
            <span>
              <%= "#{cover.unit.title} #{cover.title}" %>
            </span>

            <div class="sl-descr<%= " info_#{@unit.super_unit.layout}" unless @unit.nil? %>">
              <%= link_to t("activerecord.attributes.unit.more"), unit_by_short_url_path(cover.unit.short_url), :class => "more" %>
              <div class="title_info">
                <%= "#{cover.unit.title} #{cover.title}" %>
              </div>
            </div>
          </li>
      <% end %>
    </ul>

<style type="text/css">
    .cb-slideshow,
    .cb-slideshow:after {
        position: fixed;
        width: 100%;
        height: 100%;
        top: 0px;
        left: 0px;
        z-index: 0;
    }
    .cb-slideshow li span {
        width: 100%;
        height: 100%;
        position: absolute;
        top: 0px;
        left: 0px;
        color: transparent;
        background-size: cover;
        background-position: 50% 50%;
        background-repeat: none;
        z-index: 0;
        -webkit-backface-visibility: hidden;
        -webkit-animation: imageAnimation <%= @covers.size*delay %>s linear infinite 0s;
        -moz-animation: imageAnimation <%= @covers.size*delay %>s linear infinite 0s;
        -o-animation: imageAnimation <%= @covers.size*delay %>s linear infinite 0s;
        -ms-animation: imageAnimation <%= @covers.size*delay %>s linear infinite 0s;
        animation: imageAnimation <%= @covers.size*delay %>s linear infinite 0s;
        opacity: 0;
    }

    .cb-slideshow li .sl-descr {
        z-index: 1000;
        position: absolute;
        bottom: 21%;
        right: 0;
        text-align: right;
        opacity: 0;
        -webkit-animation: titleAnimation <%= @covers.size*delay %>s linear infinite 0s;
        -moz-animation: titleAnimation <%= @covers.size*delay %>s linear infinite 0s;
        -o-animation: titleAnimation <%= @covers.size*delay %>s linear infinite 0s;
        -ms-animation: titleAnimation <%= @covers.size*delay %>s linear infinite 0s;
        animation: titleAnimation <%= @covers.size*delay %>s linear infinite 0s;
    }

    <% @covers.each_with_index do |cover, i| %>
        .cb-slideshow li:nth-child(<%= i+1 %>) span {
            background-image: url(<%= cover.image.url(:big)%>);
            <% if i > 0 %>
                -webkit-animation-delay: <%= (i)*delay %>s;
                -moz-animation-delay: <%= (i)*delay %>s;
                -o-animation-delay: <%= (i)*delay %>s;
                -ms-animation-delay: <%= (i)*delay %>s;
                animation-delay: <%= (i)*delay %>s;
            <% end %>
        }
    <% end %>

    <% @covers.each_with_index do |cover, i| %>
        <% if i > 0 %>
        .cb-slideshow li:nth-child(<%= i+1 %>) .sl-descr {
            -webkit-animation-delay: <%= (i)*delay %>s;
            -moz-animation-delay: <%= (i)*delay %>s;
            -o-animation-delay: <%= (i)*delay %>s;
            -ms-animation-delay: <%= (i)*delay %>s;
            animation-delay: <%= (i)*delay %>s;
        }
        <% end %>
    <% end %>

    <% ["imageAnimation", "titleAnimation"].each do |animation| %>
    <% ["@-webkit-keyframes", "@-moz-keyframes", "@-o-keyframes", "@-ms-keyframes", "@keyframes"].each do |keyframe| %>
    <% if !@covers.nil? && @covers.size > 0 && animation == "imageAnimation" %>
    <%= "#{keyframe} #{animation}" %> {
    0% {
        opacity: 0;
        -webkit-animation-timing-function: ease-in;
    }
    <%= (50.to_f/@covers.size.to_f).round(0) %>% {
        opacity: 1;
        -webkit-transform: scale(1.01);
        -webkit-animation-timing-function: ease-out;
    }
    <%= (100.to_f/@covers.size.to_f).round(0) %>% {
        opacity: 1;
        -webkit-transform: scale(1.02);
    }
    <%= (150.to_f/@covers.size.to_f).round(0) %>% {
        opacity: 0;
        -webkit-transform: scale(1.03);
    }
    100% {
        opacity: 0;
    }
        }
    <% end %>

    <% if !@covers.nil? && @covers.size > 0 && animation == "titleAnimation" %>
    <%= "#{keyframe} #{animation}" %>  {
    0% {
        opacity: 0;
        z-index: 1000;
    }
    <%= (50.to_f/@covers.size.to_f).round(0) %>% {
        opacity: 1;
        z-index: 1005;
    }
    <%= (100.to_f/@covers.size.to_f).round(0) %>% {
        opacity: 1;
        z-index: 1005;
    }
    <%= (150.to_f/@covers.size.to_f).round(0) %>% {
        opacity: 0;
        z-index: 1000;
    }
    100% {
        opacity: 0;
    }
        }
    <% end %>

    <% end %>
    <% end %>

</style>
<% end %>

app/views/layouts/_slider_simple.html.erb
<% if !@unit.unit_images.nil? && @unit.unit_images.size > 1 %>
    <ul class="cb-slideshow">
      <% delay = 8 %>

      <% @unit.unit_images.each do |cover| %>
          <li>
            <span>
              <%= "#{cover.unit.title} #{cover.title}" %>
            </span>
          </li>
      <% end %>
    </ul>

    <style type="text/css">
        .cb-slideshow,
        .cb-slideshow:after {
            position: fixed;
            width: 100%;
            height: 100%;
            top: 0px;
            left: 0px;
            z-index: 0;
        }
        .cb-slideshow li span {
            width: 100%;
            height: 100%;
            position: absolute;
            top: 0px;
            left: 0px;
            color: transparent;
            background-size: cover;
            background-position: 50% 50%;
            background-repeat: none;
            z-index: 0;
            -webkit-backface-visibility: hidden;
            -webkit-animation: imageAnimation <%= @unit.unit_images.size*delay %>s linear infinite 0s;
            -moz-animation: imageAnimation <%= @unit.unit_images.size*delay %>s linear infinite 0s;
            -o-animation: imageAnimation <%= @unit.unit_images.size*delay %>s linear infinite 0s;
            -ms-animation: imageAnimation <%= @unit.unit_images.size*delay %>s linear infinite 0s;
            animation: imageAnimation <%= @unit.unit_images.size*delay %>s linear infinite 0s;
            opacity: 0;
        }
        <% @unit.unit_images.each_with_index do |cover, i| %>
        .cb-slideshow li:nth-child(<%= i+1 %>) span {
            background-image: url(<%= cover.image.url(:big)%>);
        <% if i > 0 %>
            -webkit-animation-delay: <%= (i)*delay %>s;
            -moz-animation-delay: <%= (i)*delay %>s;
            -o-animation-delay: <%= (i)*delay %>s;
            -ms-animation-delay: <%= (i)*delay %>s;
            animation-delay: <%= (i)*delay %>s;
        <% end %>
        }
        <% end %>

        <% ["imageAnimation"].each do |animation| %>
        <% ["@-webkit-keyframes", "@-moz-keyframes", "@-o-keyframes", "@-ms-keyframes", "@keyframes"].each do |keyframe| %>
        <% if !@unit.unit_images.nil? && @unit.unit_images.size > 0 && animation == "imageAnimation" %>
        <%= "#{keyframe} #{animation}" %> {
        0% {
            opacity: 0;
            -webkit-animation-timing-function: ease-in;
        }
        <%= (50.to_f/@unit.unit_images.size.to_f).round(0) %>% {
            opacity: 1;
            -webkit-transform: scale(1.01);
            -webkit-animation-timing-function: ease-out;
        }
        <%= (100.to_f/@unit.unit_images.size.to_f).round(0) %>% {
            opacity: 1;
            -webkit-transform: scale(1.02);
        }
        <%= (150.to_f/@unit.unit_images.size.to_f).round(0) %>% {
            opacity: 0;
            -webkit-transform: scale(1.03);
        }
        100% {
            opacity: 0;
        }
            }
        <% end %>

        <% end %>
        <% end %>

    </style>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title><%= yield(:title).blank? ? t('site_name') : "#{yield(:title)}" %></title>
  <meta name="description" content="<%= yield(:description) %>">
  <meta name="keywords" content="<%= yield(:keywords) %>">

  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %>
  <%= yield(:head) %>

  <%= stylesheet_link_tag :application %>
  <!--[if IE 7]><%= stylesheet_link_tag :ie7 %><![endif]-->
  <!--[if IE 8]><%= stylesheet_link_tag :ie8 %><![endif]-->
</head>

<body>
<% unless notice.nil? %>
    <p id="notice"><%= notice %></p>
<% end %>

<div id="container">
  <%= render "layouts/header" %>
  <%= yield %>
  <%= render "layouts/footer" %>
</div>
<%= yield :scripts %>

</body>
</html>

app/views/layouts/editor.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

  <title><%= yield(:title).blank? ? t('site_name') : "#{yield(:title)}" %></title>
  <meta name="description" content="<%= yield(:description) %>">
  <meta name="keywords" content="<%= yield(:keywords) %>">

  <%= javascript_include_tag :editor %>

  <%= csrf_meta_tag %>
  <%= yield(:head) %>

  <%= stylesheet_link_tag :application %>

  <!--[if IE 7]><%= stylesheet_link_tag :ie7 %><![endif]-->
  <!--[if IE 8]><%= stylesheet_link_tag :ie8 %><![endif]-->

</head>

<body class="fullheight">

<% unless notice.nil? %>
    <p id="notice"><%= notice %></p>
<% end %>

<div id="container">
  <%= render "layouts/header" %>
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/order.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

  <title><%= yield(:title).blank? ? t('site_name') : "#{yield(:title)}" %></title>
  <meta name="description" content="<%= yield(:description) %>">
  <meta name="keywords" content="<%= yield(:keywords) %>">

  <%= javascript_include_tag :editor %>

  <%= csrf_meta_tag %>
  <%= yield(:head) %>

  <%= stylesheet_link_tag :application %>

  <!--[if IE 7]><%= stylesheet_link_tag :ie7 %><![endif]-->
  <!--[if IE 8]><%= stylesheet_link_tag :ie8 %><![endif]-->

  <script type="text/javascript">
      $(document).ready(function () {
          sidebarHeight = $(window).height() - 140;
          $(".poap").css("height", sidebarHeight);

          $(window).resize(function () {
              sidebarHeight = $(window).height() - 140;
              $(".poap").css("height", sidebarHeight)
          });

      });
  </script>

</head>

<body class="fullheight">
<% unless notice.nil? %>
    <p id="notice"><%= notice %></p>
<% end %>

<div id="container">
  <%= render "layouts/header" %>
  <%= yield %>
  <%= render "layouts/footer" %>
</div>
<%= yield :scripts %>

</body>
</html>